# -*- coding: utf-8 -*-
"""Day 4-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ea4D2s4Qb8GTA-w4hvysZxVU4KXpZH_3
"""

import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from sklearn.⁹linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("train.csv")
df

df.describe()

target = "SalePrice"
num_cols = df.select_dtypes(include=[np.number]).columns.drop(target)
print(f"Numerical Columns: {len(num_cols)}\n")
num_cols

n_cols = 5
n_rows = (len(num_cols) + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(4*n_cols, 4*n_rows), tight_layout=True)
axes = axes.flatten()

for i, c in enumerate(num_cols):
    if df[c].nunique()>1:
        axes[i].scatter(df[c], df[target], alpha=0.5)
        axes[i].set_xlabel(c)
        axes[i].set_ylabel(target)
        axes[i].set_title(f"{target} vs {c}")
        axes[i].grid(True)

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.show()

X=df[["GrLivArea"]].dropna(); y=df.loc[X.index,target]
lin=LinearRegression().fit(X,y)

pred=lin.predict(X)
print("Predictions:\n",pred)

print("\n\nSlope:",lin.coef_[0])
print("Intercept:",lin.intercept_)

mse, r2 = mean_squared_error(y,pred), r2_score(y,pred)
print(f"\n\nMSE: {mse}\nR2: {r2}")

plt.figure(figsize=(6,3))
plt.scatter(X,y,alpha=0.5)
xs=np.linspace(X.min(),X.max(),200).reshape(-1,1)
plt.plot(xs,lin.predict(xs),color="red",linestyle="--")
plt.xlabel("GrLivArea"); plt.ylabel("SalePrice")
plt.legend(["Regression Line","Data Points"])
plt.grid(True,linestyle="--",alpha=0.5)
plt.title("Price vs GrLivArea")

top=df[num_cols].corrwith(df[target]).abs().sort_values(ascending=False).head(10).index.tolist()
print("Top 10 Features:\n",top)
X2=df[top].fillna(df[top].median()); y2=df[target]
Xt,Xs,Yt,Ys=train_test_split(X2,y2,test_size=0.2,random_state=0)

print(f"\nTraining Set: {Xt.shape}\nTesting Set: {Xs.shape}\nTarget Training Set: {Yt.shape}\nTarget Testing Set: {Ys.shape}")

pipe=Pipeline([("sc",StandardScaler()),("lr",LinearRegression())]).fit(Xt,Yt)
pred2=pipe.predict(Xs)
mse2, r22 = mean_squared_error(Ys,pred2), r2_score(Ys,pred2)
coefs=pd.Series(pipe.named_steps["lr"].coef_,index=X2.columns)

print("\nMSE:",mse2," R2:",r22," Intercept:",pipe.named_steps["lr"].intercept_)
print("\n\nColumn\t\t | \tCoefficients\t\t | \t\tSlope\t\t")
print("--"*40)
for i,col in enumerate(top):
    print(f"{col}\t | \t{coefs[i]}\t | \t{pipe.named_steps['lr'].coef_[i]}")

print("\n\n")
plt.figure(figsize=(8,4))
sns.heatmap(df[top].corr(),annot=True,cmap="magma")
plt.title("Correlation Matrix")
plt.show()

