# -*- coding: utf-8 -*-
"""Day 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jze2zgeRaq3b1jTO7fuW6u0Hg-jzUGM4
"""

import numpy as np, pandas as pd, seaborn as sns, matplotlib.pyplot as plt

"""## Q1. Data Loading & Cleaning"""

df = sns.load_dataset("titanic")
df.head()

print(df.isna().sum())

df['age'] = df['age'].fillna(df['age'].median())
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df = df.drop('deck', axis=1)
df

print(df.isna().sum().sum())

print(df.duplicated().sum())
df=df.drop_duplicates()
print(df.duplicated().sum())

"""## Q2. Exploratory Data Analysis (EDA)"""

df.describe(include=['object'])

df.describe()

num_cols = df.select_dtypes(include=['number']).columns
plt.figure(figsize=(6, 3))
sns.heatmap(df[num_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features')
plt.show()

axes = plt.subplots(1, 3, figsize=(20, 5))[1]
sns.barplot(x='sex', y='survived', data=df,  ax=axes[0])
sns.barplot(x='pclass', y='survived', data=df,  ax=axes[1])
sns.countplot(x='age', data=df,  ax=axes[2])
axes[0].set_title('Sex vs Survived')
axes[1].set_title('Pclass vs Survived')
axes[2].set_title('Age Distribution')
plt.show()

"""## Q3. Feature Engineering"""

df = pd.get_dummies(df, columns=['sex', 'embarked', 'class'], drop_first=True)
df.head()

df['family_size'] = df['sibsp'] + df['parch'] + 1
df.head()

df['is_alone'] = (df['family_size'] == 1).astype(int)
df.head()

bins = [0, 12, 18, 60, 100]
labels = ['child', 'teen', 'adult', 'senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)
df['age_group'].value_counts()

"""## Q4. Dimensionality Reduction"""

from sklearn.preprocessing import StandardScaler

features_to_scale = ['age', 'fare', 'family_size']
scaler = StandardScaler()
df[features_to_scale] = scaler.fit_transform(df[features_to_scale])

df.head()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

pca_features = ['pclass', 'age', 'sibsp', 'parch', 'fare',
                'sex_male', 'embarked_Q', 'embarked_S', 'class_Second', 'class_Third',
                'family_size', 'is_alone']

X_pca = df[pca_features].copy()

for col in ['sex_male', 'embarked_Q', 'embarked_S', 'class_Second', 'class_Third']:
    if col in X_pca.columns and X_pca[col].dtype == 'bool':
        X_pca[col] = X_pca[col].astype(int)

scaler_for_pca = StandardScaler()
X_pca_scaled = scaler_for_pca.fit_transform(X_pca)
X_pca_transformed = pca.fit_transform(X_pca_scaled)

pca_df = pd.DataFrame(data=X_pca_transformed, columns=['principal_component_1', 'principal_component_2'])

print("First 5 rows of the DataFrame with 2 Principal Components:")
print(pca_df.head())
print("\nExplained variance ratio of the components:")
print(pca.explained_variance_ratio_)
print("Total explained variance:", pca.explained_variance_ratio_.sum())

"""## Q5. Feature Selection"""

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

y = df['survived']
feature_cols = ['pclass', 'age', 'sibsp', 'parch', 'fare',
                'sex_male', 'embarked_Q', 'embarked_S', 'class_Second', 'class_Third',
                'family_size', 'is_alone']
X = df[feature_cols].copy()

for col in ['sex_male', 'embarked_Q', 'embarked_S', 'class_Second', 'class_Third']:
    if col in X.columns and X[col].dtype == 'bool':
        X[col] = X[col].astype(int)

minmax_scaler = MinMaxScaler()
columns_to_minmax_scale = ['age', 'fare', 'family_size']
X[columns_to_minmax_scale] = minmax_scaler.fit_transform(X[columns_to_minmax_scale])

selector = SelectKBest(chi2, k=5)
X_new = selector.fit_transform(X, y)

selected_features_mask = selector.get_support()
selected_features = X.columns[selected_features_mask]

print("Top 5 features selected by chi2 test:")
print(selected_features.tolist())

